# Generated by Django 3.1.1 on 2020-10-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_auto_20201010_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impresora',
            name='delete',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha baja'),
        ),
    ]
